2021-06-26 21:14:18,194 - root - INFO - Test set results:
2021-06-26 21:14:18,194 - root - INFO - AUC: 0.57734
2021-06-26 21:14:18,194 - root - INFO - Maximum micro F1: 0.57243
2021-06-26 21:14:18,194 - root - INFO - Maximum macro F1: 0.04403
2021-06-26 21:14:18,194 - root - INFO - Micro F1: 0.50013
2021-06-26 21:14:18,194 - root - INFO - Macro F1: 0.02438
2021-06-26 21:14:18,194 - root - INFO - P@100: 0.96000
2021-06-26 21:14:18,194 - root - INFO - P@200: 0.93500
2021-06-26 21:14:18,194 - root - INFO - P@300: 0.88000
Traceback (most recent call last):
  File "train_bag_cnn.py", line 178, in <module>
    np.save('result/{}_p.npy'.format(args.result), result['np_prec'])
  File "<__array_function__ internals>", line 6, in save
  File "/home/yz/anaconda3/lib/python3.6/site-packages/numpy/lib/npyio.py", line 541, in save
    fid = open(file, "wb")
FileNotFoundError: [Errno 2] No such file or directory: 'result/_p.npy'